### PR TITLE
Migrate threats made against legal researchers to: https://github.com/disclose/research-threats

### PR DESCRIPTION
**Pull request by sickcodes**
Migrate threats made against legal researchers to: https://github.com/disclose/research-threats

### CODE REVIEW

**Comment by sickcodes** [comment]
And some README.md changes! 

Preview: https://github.com/sickcodes/diodata/tree/migrate-threats

**Comment by attritionorg** [comment]
Add a bullet that encourages people to contribute via Issue or PR?

**Comment by sickcodes** [comment]
Should be just below, but I can add in the bullet points too if you think it stands out a bit more?

https://github.com/sickcodes/diodata/tree/migrate-threats#community-powered--open-source-data

**Comment by attritionorg** [comment]
deleted my comment quick. ignore me, i commented before i read the whole thing =)

**Comment by yesnet0** [comment]
Hey @sickcodes would you mind redoing the PR?

**Pull request merged**
